import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from "@/app/components/NavBar";
import React from "react";
import AuthProvider from "@/context/AuthProvider";
import Providers from "@/app/components/Providers";
import Appbar from "@/app/components/AppBar";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <html lang="en">
      <body className={inter.className}>
      <Providers>
          <Appbar/>
          {children}
      </Providers>
      </body>
      </html>
  )
}
